name: Release GitHub Page

on:
  push:
    branches:
      - develop
    pull_request:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          npm install
          npm run build
        env:
          REACT_APP_DJANGO_URL: ${{ secrets.REACT_APP_DJANGO_URL }}
          REACT_APP_DJANGO_WS_URL: ${{ secrets.REACT_APP_DJANGO_WS_URL }}

      # - name: Test
      #   run: |
      #     yarn test
      #   working-directory: app

      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
