name: Release GitHub Page

on:
  push:
    branches:
      - develop
    pull_request:
      - develop

jobs:
  build_test_deploy:
    runs-on: ubuntu-21.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1

      - name: Install Dependencies
        run: |
          npm install
        working-directory: app

      - name: Build
        run: |
          npm build
        working-directory: app

      # - name: Test
      #   run: |
      #     yarn test
      #   working-directory: app

      - name: App Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public